version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:2022.07.1
      docker_layer_caching: true
    resource_class: arm.large
    steps:
      - checkout
      - run:
          name: Build sorbet-static gem
          command: ./build.sh
workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
                - an--debugging
