version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:current
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build sorbet-static gem
          command: ./build.sh
workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              only: main
