version: 2.1

parameters:
  sorbet-version:
    type: string
    default: ""

jobs:
  build:
    machine:
      image: ubuntu-2004:current
      docker_layer_caching: true
    resource_class: arm.large
    steps:
      - checkout
      - run: &version
          name: Set Sorbet version
          command: export SORBET_VERSION='${{ parameters.sorbet-version }}'
      - run: &build
          name: Build sorbet-static gem
          command: ./build.sh
  build-and-publish:
    machine:
      image: ubuntu-2004:current
      docker_layer_caching: true
    resource_class: arm.large
    steps:
      - checkout
      - run: *version
      - run: *build
      - run:
          name: Pubish sorbet-static to Gemfury
          command: ./publish.sh

workflows:
  build-only:
    when:
      and:
        - not:
            matches:
              pattern: "^main$"
              value: << pipeline.git.branch >>
    jobs:
      - build
  build-and-publish:
    when:
      and:
        - equal: [ << pipeline.git.branch >>, main ]
    jobs:
      - build-and-publish
